# Generated by Django 3.2.5 on 2021-08-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student_class'),
        ),
    ]
